language: cpp
before_install:
- sudo apt-get install -y libgd-dev libpng-dev libjpeg-dev
script: make
before_deploy:
- git config --local user.name "soruly"
- git config --local user.email "soruly@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: lXNGkX2KKLFT8Z+e/B9/ebnawgeRC5IIv87UefO5a7q/kPHDZ8TJAT9dT66+1lyiak5NpsAIAl865dSmuzzgqShUki971TyZ46RIFBoNO/36FfrqRM+aBjNoenvB+7hUWZzTMIQHQ6QgMIc+iule8tsEWbpOOxuUccPRKh1V/ObLw+X4eDUtnNM5uimk4/u5uQ8tA1NVyuExmXjRPNLn6213jLLPcGIxXEE0shpVQwaKRQtMwRIwHS88n8pcbNWT1ZSEQuvmYC040gXI6+0s45wHqTspS+ddngBeX8xKOaHsz1rJCJKKqI6dtO1QAly32nTRG9Ld624ffWCiqwS4XFYeCeVwwDqMg73Zy9MgRN7viDaDyYcDgz7H1vjeqN1OuzLML7bvNhDgHK+y9omcpcYNpLdg6OjDBUTSCQC9jYRUIvpy7Lp+05k5WMzWH1WWlRkMb0XnWduvcuLGVTtYjIAfe9wGAmaz8Cd6oc8AFIJGUerkoeeOwlqPyxA4yZIsYNq4XrLv1rejdG2VlIaPm3fEFz3HcuF/5ObpTNrkhlyRbYO3Vb8JUA5B5q4CJFsfop259xXZaJ/OqOfi/xoV2Y7sdNVR7dZ8U/ALGD5y8hFk9qBtMqwb8yZW5qIBiwWZOylhQP5wYTtWkXYZx3DOz6JXEynbXpm5F8cMSJal6f4=
  file: iqdb
  on:
    repo: soruly/iqdb
