language: cpp
before_install:
  - sudo apt-get install -y libgd-dev libpng-dev libjpeg-dev
script: make
deploy:
  provider: releases
  api_key: 1df2767507c2985581d9f5b2afe6e8f7acda7232
  file: "iqdb"
  skip_cleanup: true
  on:
    tags: true

